'\" t
.\"     Title: nntp-list
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/10/2014
.\"    Manual: nntp-list manual
.\"    Source: nntp-list 1.5.2
.\"  Language: English
.\"
.TH "NNTP\-LIST" "1" "2014-07-10" "nntp-list 1\&.5\&.2" "nntp-list manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nntp-list \- print a list of available newsgroups
.SH "SYNOPSIS"
.HP \w'\fBnntp\-list\fR\ 'u
\fBnntp\-list\fR [\fIoptions\fR...]
.SH "DESCRIPTION"
.PP
Print a list of available newsgroups to the standard output\&.
.PP
This commands takes neither command\-specific options nor arguments\&.
.PP
Global options are described in
\fBsinntp\fR(1)\&.
.SH "SEE ALSO"
.PP
\fBsinntp\fR(1)
.SH "COPYRIGHT"
.br
Copyright \(co 2009, 2010, 2011, 2012 Piotr Lewandowski, Jakub Wilk
.br
